### ISSUE TITLE
не работает графана

### ISSUE THREAD

**Issue by IvanLotoff** [kirya522/medium-posts#1]
Привет, я склонил проект и запустил его. Прометеус работает отлично, однако графана нет 

![image](https://user-images.githubusercontent.com/71568721/153042840-198c6629-12e0-4d76-b5d1-549e82dca79f.png)
![image](https://user-images.githubusercontent.com/71568721/153042882-307bf097-c68f-46b7-b1e7-3c5833df30be.png)

Возникает ошибка 
AnnotationQueryRunner failed
Query error: 400 Bad Request

**Comment by kirya522** [comment]
Merged protocol fixes, should work now
